//
//  SourceView.swift
//  XplistScalpel
//
//  "Show Plist Text": a read-only, selectable XML rendering of the current
//  tree, generated by the order-preserving writer.
//

import SwiftUI

struct SourceView: View {
    let doc: PlistDocument

    private var source: String { XMLPlistWriter.string(from: doc.root) }

    var body: some View {
        ScrollView([.vertical, .horizontal]) {
            Text(source)
                .font(.system(.body, design: .monospaced))
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(12)
        }
        .background(Color(nsColor: .textBackgroundColor))
        .overlay(alignment: .topTrailing) {
            Button {
                let pasteboard = NSPasteboard.general
                pasteboard.clearContents()
                pasteboard.setString(source, forType: .string)
            } label: {
                Label("Copy", systemImage: "doc.on.doc")
            }
            .buttonStyle(.bordered)
            .padding(12)
        }
    }
}
